export const products = [
  {
    id: "65bf49743eda8f76799a9578",
    name: "Basic Package",
    description:
      "Principal return on maturity, instant withdrawal to your mobile money or bank profession chart and 24/7 support. package maturity time 24-25 hours maximum",
    price: "50",
    profit: "248",
    category: "Student Plan",
    availability: true,
    personalAccount: true,
    swapdiscount: false,
    customizedinvestment: false,
    color: "green",
  },
  {
    id: "65bf49743eda8f76799a9539",
    name: "Basic Package",
    description:
      "Principal return on maturity, instant withdrawal to your mobile money or bank profession chart and 24/7 support. package maturity time 24-25 hours maximum",
    price: "105",
    profit: "474",
    category: "Hustler Plan",
    availability: true,
    personalAccount: true,
    swapdiscount: false,
    customizedinvestment: false,
    color: "blue",
  },
  {
    id: "65bf49743eda8f76799349535",
    name: "Basic Package",
    description:
      "Principal return on maturity, instant withdrawal to your mobile money or bank profession chart and 24/7 support. package maturity time 24-25 hours maximum",
    price: "210",
    profit: "1021",
    category: "Builder Plan",
    availability: true,
    personalAccount: true,
    swapdiscount: false,
    customizedinvestment: false,
    color: "purple",
  },
  {
    id: "65bf49743eda8f76799a9535",
    name: "Basic Package",
    description:
      "Principal return on maturity, instant withdrawal to your mobile money or bank profession chart and 24/7 support. package maturity time 24-25 hours maximum",
    price: "500",
    profit: "3000",
    category: "Legacy Plan",
    availability: true,
    personalAccount: true,
    swapdiscount: false,
    customizedinvestment: false,
    color: "yellow",
  },
];
