export const products = [
  // {
  //   id: "1",
  //   name: "Basic Package",
  //   description:
  //     "Principal return on maturity, instant withdrawal to your mobile money or bank profession chart and 24/7 support. package maturity time 24-25 hours maximum",
  //   price: "50",
  //   profit: "280",
  //   category: "Student Plan",
  //   availability: true,
  //   personalAccount: true,
  //   swapdiscount: false,
  //   customizedinvestment: false,
  //   color: "special",
  //   type: true,
  // },
  {
    id: "2",
    name: "Basic Package",
    description:
      "Principal return on maturity, instant withdrawal to your mobile money or bank profession chart and 24/7 support. package maturity time 24-25 hours maximum",
    price: "105",
    profit: "474",
    category: "Hustler Plan",
    availability: true,
    personalAccount: true,
    swapdiscount: false,
    customizedinvestment: false,
    color: "blue",
    type: false,
  },
  {
    id: "3",
    name: "Basic Package",
    description:
      "Principal return on maturity, instant withdrawal to your mobile money or bank profession chart and 24/7 support. package maturity time 24-25 hours maximum",
    price: "210",
    profit: "1021",
    category: "Builder Plan",
    availability: true,
    personalAccount: true,
    swapdiscount: false,
    customizedinvestment: false,
    color: "purple",
    type: false,
  },
  {
    id: "4",
    name: "Basic Package",
    description:
      "Principal return on maturity, instant withdrawal to your mobile money or bank profession chart and 24/7 support. package maturity time 24-25 hours maximum",
    price: "500",
    profit: "3000",
    category: "Legacy Plan",
    availability: true,
    personalAccount: true,
    swapdiscount: false,
    customizedinvestment: false,
    color: "yellow",
    type: false,
  },
];
